export const DATABASE = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACES = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES_ID!;
export const IMAGES_BUCKET = process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!;
